export enum EntityEnum{
    PROSPECT = 'PROSPECT',
    INTERACTION = 'INTERACTION',
    INTERLOCUTOR = 'INTERLOCUTOR',
    STORAGENEED = 'STORAGENEED',
    STORAGEOFFER = 'STORAGEOFFER',
    STORAGECONTRACT = 'STORAGECONTRACT',
    STORAGEINVOICE = 'STORAGEINVOICE',
    STORAGNOTE = 'STORAGNOTE',
    CUSTOMER = 'CUSTOMER',
    COMPANY = 'COMPANY',
}
