import {LegalStatusDto} from "../init_data/response/legal.status.dto";
import {CityResponseDto} from "../init_data/response/city.response.dt";
import {CourtResponseDto} from "../init_data/response/court.response.dto";
import {CompanySizeResponseDto} from "../init_data/response/company.size.response.dt";
import {IndustryResponseDto} from "../init_data/response/industry.response.dt";
import {CountryResponseDto} from "../init_data/response/country.response.dto";
import {ProprietaryStructureDto} from "../init_data/response/proprietary.structure.dto";
import {JobTitleResponseDto} from "../init_data/response/job.title.response.dto";
import {TitleResponseDto} from "../init_data/response/title.response.dto";

export class CompanyResponseDto {
  createdAt: string;
  updatedAt: string;
  deletedAt: string | null;
  createdBy: string | null;
  id: number;
  logo: string;
  name: string;
  sigle: string;
  capital: number;
  headOffice: string;
  legalRepresentative: string;
  yearOfCreation: string;
  dateOfRegistration: string;
  email: string;
  phone: string;
  fax: string;
  whatsapp: string;
  website: string;
  linkedin: string;
  ice: string;
  rc: string;
  ifm: string;
  patent: string;
  cnss: string;
  businessDescription: string;
  legalStatus: LegalStatusDto;
  city: CityResponseDto;
  court: CourtResponseDto;
  companySize: CompanySizeResponseDto;
  industry: IndustryResponseDto;
  country: CountryResponseDto;
  proprietaryStructure: ProprietaryStructureDto;
  title: TitleResponseDto;
  reprosentaveJobTitle: JobTitleResponseDto;
  certificationText: string | null;

  constructor(data: any) {
    this.createdAt = data.createdAt;
    this.updatedAt = data.updatedAt;
    this.deletedAt = data.deletedAt;
    this.createdBy = data.createdBy;
    this.id = data.id;
    this.logo = data.logo;
    this.name = data.name;
    this.sigle = data.sigle;
    this.capital = data.capital;
    this.headOffice = data.headOffice;
    this.legalRepresentative = data.legalRepresentative;
    this.yearOfCreation = data.yearOfCreation;
    this.dateOfRegistration = data.dateOfRegistration;
    this.email = data.email;
    this.phone = data.phone;
    this.fax = data.fax;
    this.whatsapp = data.whatsapp;
    this.website = data.website;
    this.linkedin = data.linkedin;
    this.ice = data.ice;
    this.rc = data.rc;
    this.ifm = data.ifm;
    this.patent = data.patent;
    this.cnss = data.cnss;
    this.businessDescription = data.businessDescription;
    this.legalStatus = data.legalStatus ? new LegalStatusDto(data.legalStatus) : null as any;
    this.city = data.city ? new CityResponseDto(data.city) : null as any;
    this.court = data.court ? new CourtResponseDto(data.court) : null as any;
    this.companySize = data.companySize ? new CompanySizeResponseDto(data.companySize) : null as any;
    this.industry = data.industry ? new IndustryResponseDto(data.industry) : null as any;
    this.country = data.country ? new CountryResponseDto(data.country) : null as any;
    this.proprietaryStructure = data.proprietaryStructure ? new ProprietaryStructureDto(data.proprietaryStructure) : null as any;
    this.title = data.title ? new TitleResponseDto(data.title) : null as any;
    this.reprosentaveJobTitle = data.reprosentaveJobTitle ? new JobTitleResponseDto(data.reprosentaveJobTitle) : null as any;
    this.certificationText = data.certificationText;
  }
}
