import { LegalStatusModel } from '../init_data_models/legalStatus.model';
import { CityModel } from '../init_data_models/city.model';
import { CourtModel } from '../init_data_models/court.model';
import { IndustryModel } from '../init_data_models/industry.model';
import { CountryModel } from '../init_data_models/country.model';
import { ProprietaryStructureModel } from '../init_data_models/proprietaryStructure.model';
import { TitleModel } from '../init_data_models/title.model';
import { JobTitleModel } from '../init_data_models/jobTitle.model';
import { CompanySizeModel } from '../init_data_models/companySize.model';

export class CompanyModel {
    createdAt: Date;
    updatedAt: Date | null;
    deletedAt: Date | null;
    createdBy: string;
    id: number;
    logo: string;
    name: string;
    sigle: string;
    capital: number;
    headOffice: string;
    legalRepresentative: string;
    yearOfCreation: number;
    dateOfRegistration: string;
    email: string;
    phone: string;
    fax: string;
    whatsapp: string;
    website: string;
    linkedin: string;
    ice: string;
    rc: string;
    ifm: string;
    patent: string;
    cnss: string;
    businessDescription: string;
    legalStatus: LegalStatusModel;
    city: CityModel;
    court: CourtModel;
    companySize: CompanySizeModel;
    industry: IndustryModel;
    country: CountryModel;
    proprietaryStructure: ProprietaryStructureModel;
    title: TitleModel;
    reprosentaveJobTitle: JobTitleModel;
    certificationText: string | null;

    constructor(data: any) {
        this.createdAt = new Date(data.createdAt);
        this.updatedAt = data.updatedAt ? new Date(data.updatedAt) : null;
        this.deletedAt = data.deletedAt ? new Date(data.deletedAt) : null;
        this.createdBy = data.createdBy;
        this.id = data.id;
        this.logo = data.logo;
        this.name = data.name;
        this.sigle = data.sigle;
        this.capital = data.capital;
        this.headOffice = data.headOffice;
        this.legalRepresentative = data.legalRepresentative;
        this.yearOfCreation = data.yearOfCreation;
        this.dateOfRegistration = data.dateOfRegistration;
        this.email = data.email;
        this.phone = data.phone;
        this.fax = data.fax;
        this.whatsapp = data.whatsapp;
        this.website = data.website;
        this.linkedin = data.linkedin;
        this.ice = data.ice;
        this.rc = data.rc;
        this.ifm = data.ifm;
        this.patent = data.patent;
        this.cnss = data.cnss;
        this.businessDescription = data.businessDescription;
        this.legalStatus = new LegalStatusModel(data.legalStatus);
        this.city = new CityModel(data.city);
        this.court = new CourtModel(data.court);
        this.companySize = new CompanySizeModel(data.companySize);
        this.industry = new IndustryModel(data.industry);
        this.country = new CountryModel(data.country);
        this.proprietaryStructure = new ProprietaryStructureModel(data.proprietaryStructure);
        this.title = new TitleModel(data.title);
        this.reprosentaveJobTitle = new JobTitleModel(data.reprosentaveJobTitle);
        this.certificationText = data.certificationText;
    }
}
