import { LegalStatusModel } from '../init_data_models/legalStatus.model';
import { CityModel } from '../init_data_models/city.model';
import { CourtModel } from '../init_data_models/court.model';
import { IndustryModel } from '../init_data_models/industry.model';
import { CountryModel } from '../init_data_models/country.model';
import { ProprietaryStructureModel } from '../init_data_models/proprietaryStructure.model';
import { TitleModel } from '../init_data_models/title.model';
import { JobTitleModel } from '../init_data_models/jobTitle.model';
import { CompanySizeModel } from '../init_data_models/companySize.model';
import {UserDto} from '../../../dtos/response/usersResponseDto';

export class CompanyModel {
    createdAt: Date;
    updatedAt: Date ;
    deletedAt: Date | null;
    createdBy: UserDto;
    updatedBy: UserDto;
    id: number;
    logo: string;
    name: string;
    sigle: string;
    capital: number;
    headOffice: string;
    legalRepresentative: string;
    yearOfCreation: string;
    dateOfRegistration: string;
    email: string;
    phone: string;
    fax: string;
    whatsapp: string;
    website: string;
    linkedin: string;
    ice: string;
    rc: string;
    ifm: string;
    patent: string;
    cnss: string;
    businessDescription: string;
    legalStatus: LegalStatusModel;
    city: CityModel;
    court: CourtModel;
    companySize: CompanySizeModel;
    industry: IndustryModel;
    country: CountryModel;
    proprietaryStructure: ProprietaryStructureModel;
    title: TitleModel;
    reprosentaveJobTitle: JobTitleModel;
    certificationText: string | null;

    constructor(data: any) {
        this.createdAt = new Date(data.createdAt);
        this.updatedAt = data.updatedAt ;
        this.deletedAt = data.deletedAt ? new Date(data.deletedAt) : null;
        this.createdBy = data.createdBy;
        this.id = data.id;
        this.logo = data.logo;
        this.name = data.name;
        this.sigle = data.sigle;
        this.capital = data.capital;
        this.headOffice = data.headOffice;
        this.legalRepresentative = data.legalRepresentative;
        this.yearOfCreation = data.yearOfCreation;
        this.dateOfRegistration = data.dateOfRegistration;
        this.email = data.email;
        this.phone = data.phone;
        this.fax = data.fax;
        this.whatsapp = data.whatsapp;
        this.website = data.website;
        this.linkedin = data.linkedin;
        this.ice = data.ice;
        this.rc = data.rc;
        this.ifm = data.ifm;
        this.patent = data.patent;
        this.cnss = data.cnss;
        this.businessDescription = data.businessDescription;
        this.legalStatus = data.legalStatus ? (data.legalStatus instanceof LegalStatusModel ? data.legalStatus : new LegalStatusModel(data.legalStatus)) : null as any;
        this.city = data.city ? (data.city instanceof CityModel ? data.city : new CityModel(data.city)) : null as any;
        this.court = data.court ? (data.court instanceof CourtModel ? data.court : new CourtModel(data.court)) : null as any;
        this.companySize = data.companySize ? (data.companySize instanceof CompanySizeModel ? data.companySize : new CompanySizeModel(data.companySize)) : null as any;
        this.industry = data.industry ? (data.industry instanceof IndustryModel ? data.industry : new IndustryModel(data.industry)) : null as any;
        this.country = data.country ? (data.country instanceof CountryModel ? data.country : new CountryModel(data.country)) : null as any;
        this.proprietaryStructure = data.proprietaryStructure ? (data.proprietaryStructure instanceof ProprietaryStructureModel ? data.proprietaryStructure : new ProprietaryStructureModel(data.proprietaryStructure)) : null as any;
        this.title = data.title ? (data.title instanceof TitleModel ? data.title : new TitleModel(data.title)) : null as any;
        this.reprosentaveJobTitle = data.reprosentaveJobTitle ? (data.reprosentaveJobTitle instanceof JobTitleModel ? data.reprosentaveJobTitle : new JobTitleModel(data.reprosentaveJobTitle)) : null as any;
        this.certificationText = data.certificationText;
        this.updatedBy = data.updatedBy;
    }
}
